# Generated by Django 2.2.12 on 2020-08-15 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ay', models.CharField(max_length=100)),
                ('status', models.NullBooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AOSF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athletic_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('internet_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('cultural_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('guidance_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('handbook_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('laboratory_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('computer_laboratory_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('medical_and_dental_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('registration_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('entrance_exam', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('school_id_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('development_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('library_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('tution_fee_ammount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('insurance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DaySched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('number_of_days', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollbyStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_key', models.SlugField(null=True)),
                ('semister', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollbyStudents', to='student_profile.Academic_year')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollbyStudents', to='student_profile.Course')),
            ],
            options={
                'ordering': ['major', 'year_level', 'student'],
            },
        ),
        migrations.CreateModel(
            name='IDandFullname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('unit', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UploadExcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='xls/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('duration_in_hour', models.FloatField(default=1)),
                ('days', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student_profile.DaySched')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectsLoaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_status', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('enrolled_by_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enroll_subjects', to='student_profile.EnrollbyStudent')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student_profile.Instructor')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('ext_name', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField(null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('brgy', models.CharField(max_length=200, null=True)),
                ('street', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('province', models.CharField(max_length=200, null=True)),
                ('place_of_birth', models.CharField(max_length=200, null=True)),
                ('mobile_no', models.CharField(max_length=40, null=True)),
                ('guardian', models.CharField(max_length=200, null=True)),
                ('relationship', models.CharField(max_length=200, null=True)),
                ('guardian_address', models.CharField(max_length=200, null=True)),
                ('guardian_contact', models.CharField(max_length=200, null=True)),
                ('occupation', models.CharField(max_length=200, null=True)),
                ('religion', models.CharField(max_length=200, null=True)),
                ('zip_code', models.CharField(max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('primary', models.CharField(max_length=200, null=True)),
                ('elementary', models.CharField(max_length=200, null=True)),
                ('highschool', models.CharField(max_length=200, null=True)),
                ('degree_completed', models.CharField(blank=True, max_length=200, null=True)),
                ('degree_year_attended', models.CharField(blank=True, max_length=8, null=True)),
                ('name_of_school', models.CharField(blank=True, max_length=200, null=True)),
                ('primary_completed', models.CharField(max_length=8, null=True)),
                ('elementary_completed', models.CharField(max_length=8, null=True)),
                ('highschool_completed', models.CharField(max_length=8, null=True)),
                ('civil_status', models.CharField(max_length=200, null=True)),
                ('nationality', models.CharField(max_length=200, null=True)),
                ('email_add', models.CharField(max_length=200, null=True)),
                ('lrn_num', models.CharField(max_length=200, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student_profile.Course')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student_profile.Major')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='InstructorLoadSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semister', models.CharField(max_length=20)),
                ('section', models.CharField(default='A', max_length=2)),
                ('is_lab', models.NullBooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student_profile.Academic_year')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.Instructor')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.Major')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Room')),
                ('schedule_days', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.DaySched')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Subject')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.TimeSched')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Year_level')),
            ],
        ),
        migrations.CreateModel(
            name='GradeSubmitted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, null=True)),
                ('intructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Instructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='enrollbystudent',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollbyStudents', to='student_profile.Major'),
        ),
        migrations.AddField(
            model_name='enrollbystudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollbyStudents', to='student_profile.Student'),
        ),
        migrations.AddField(
            model_name='enrollbystudent',
            name='year_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollbyStudents', to='student_profile.Year_level'),
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('semister', models.CharField(max_length=20, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Course')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.Major')),
                ('subjects', models.ManyToManyField(related_name='Curriculum_subjects', to='student_profile.Subject')),
                ('year_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.Year_level')),
            ],
        ),
    ]
