# Generated by Django 2.2.12 on 2020-08-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0002_studentuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
