# Generated by Django 2.1.1 on 2020-08-25 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0003_auto_20200817_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorLoadCourseMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_load_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_load_subject', to='student_profile.InstructorLoadSubject')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.Major')),
            ],
        ),
    ]
