# Generated by Django 2.1.1 on 2020-08-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0004_instructorloadcoursemajor'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorloadsubject',
            name='major_ids',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
